### ISSUE TITLE
autocompletion is calling /metadata instead of /labels and /series

### ISSUE THREAD

**Issue by stenwolf** [prometheus/codemirror-promql#186]
Hello,
I'm trying to use the autocomplete feature, this is how I'm setting up my promQL extention:

`const promQL = new PromQLExtension().setComplete({
            remote: {
                apiPrefix: '/v1/prom',
                httpMethod: 'GET'
            }
        });`

From the Readme file, it's saying by default it is calling `/api/v1/labels` and `/api/v1/series`. But i don't see these calls being triggered, I'm only seeing `/v1/prom/metadata` being triggered.

Reason why I can't use the `metadata` endpoint being, it is sending back all of the metrics from all of the instances, and I'm not able to pass in a query to the `metadata` endpoint. On the other hand, `labels` and `metrics` allow me to send in a query so i can setup a proxy and send in a query to filter the response by instances.

So is there a way i can set the autocomplete feature to make GET requests to the `labels` and the `series` endpoints instead of the `metadata` endpoint?

**Comment by Nexucis** [comment]
Hello @stenwolf 

Hopefully changing the HTTP Method used shouldn't change or block the queries going to `/v1/prom/labels` and to `/v1/prom/series` and it is the regular behaviour that the autocompletion feature is asking to these two endpoints to get the required info.
The usage of the metadata endpoint is here to display the metrics helper during the autocompletion. But it's only happening if there is not too much metadata to get.

Do you have some errors in the browser console ?
Which version of `codemirror-promql` are you using ? With which version of `codemirror` ? 

Is it possible to see how did you integrate `codemirror-promql` ?

I look at the code and I didn't find why the code would have the behaviour your are describing. I'm not saying there is no issue, I'm just saying that so far I don't explain or understand how to code is doing what you are experimenting.

**Comment by stenwolf** [comment]
Hi, I don't see any related error in console, the only one is 404 for the /v1/prom/metadata, it's because i dont want to expose this endpoint. Speaking of that, is there a way for me to specify i don't want metadata endpoint to be called? If not I guess i can create a proxy endpoint and just returns nothing.

For the versions, im using `"codemirror-promql": "0.19.0",` and these are the versions im using for codemirror
```
    "@codemirror/autocomplete": "0.19.14",
    "@codemirror/basic-setup": "0.19.1",
    "@codemirror/highlight": "0.19.7",
    "@codemirror/language": "0.19.8",
    "@codemirror/lint": "0.19.6",
    "@codemirror/state": "0.19.9",
    "@codemirror/view": "0.19.47",
```

this is how I set up my codemirror-promql

```javascript
        const promQL = new PromQLExtension().setComplete({
            remote: {
                apiPrefix: '/v1/tsdb',
                httpMethod: 'GET',
            },
        });

        const defaultExtentions = [
            enterKey(),
            basicSetup,
            promQL.asExtension(),
            EditorView.updateListener.of(editorViewUpdateListener),
        ];

        editorView = new EditorView({
                state: EditorState.create({
                    extensions: [
                        ...defaultExtentions,
                        ...themeOptions[currentTheme.value],
                    ],
                }),
                parent: document.getElementById(editorID.value),
            });
```

**Comment by stenwolf** [comment]
Hi, I don't see any related error in console, the only one is 404 for the /v1/prom/metadata, it's because i dont want to expose this metadata endpoint. Speaking of that, is there a way for me to specify i don't want metadata endpoint to be called? If not I guess i can create a proxy endpoint and just returns nothing.

For the versions, im using `"codemirror-promql": "0.19.0",` and these are the versions im using for codemirror
```
    "@codemirror/autocomplete": "0.19.14",
    "@codemirror/basic-setup": "0.19.1",
    "@codemirror/highlight": "0.19.7",
    "@codemirror/language": "0.19.8",
    "@codemirror/lint": "0.19.6",
    "@codemirror/state": "0.19.9",
    "@codemirror/view": "0.19.47",
    "codemirror-promql": "0.19.0",
```

this is how I set up my codemirror-promql

```javascript
        const promQL = new PromQLExtension().setComplete({
            remote: {
                apiPrefix: '/v1/prom',
                httpMethod: 'GET',
            },
        });

        const defaultExtentions = [
            enterKey(),
            basicSetup,
            promQL.asExtension(),
            EditorView.updateListener.of(editorViewUpdateListener),
        ];

        editorView = new EditorView({
            state: EditorState.create({
                extensions: [
                    ...defaultExtentions,
                    ...themeOptions[currentTheme.value],
                ],
            }),
            parent: document.getElementById(editorID.value)
        });
```

**Comment by Nexucis** [comment]
Thanks for details provided.

I tried to reproduce the issue and so far I didn't success :(.

Here what I have:

* index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PromQL</title>
</head>
<body>
<div id=editor></div>
</body>
</html>
```

* index.ts

```typescript
import {PromQLExtension} from "codemirror-promql";
import {EditorView} from "@codemirror/view";
import {EditorState} from "@codemirror/state";
import {basicSetup} from "@codemirror/basic-setup";

const promQL = new PromQLExtension().setComplete({
    remote: {
        apiPrefix: '/v1/prom',
        httpMethod: 'GET',
    },
});

new EditorView({
    state: EditorState.create({
        extensions: [basicSetup, promQL.asExtension()],
        doc: '',
    }),
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    parent: document.querySelector('#editor')!,
});
```

* package.json

```json
{
  "name": "cmp-investigation",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "webpack serve --config webpack.dev.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@codemirror/autocomplete": "0.19.14",
    "@codemirror/basic-setup": "0.19.1",
    "@codemirror/highlight": "0.19.7",
    "@codemirror/language": "0.19.8",
    "@codemirror/lint": "0.19.6",
    "@codemirror/state": "0.19.9",
    "@codemirror/view": "0.19.47",
    "codemirror-promql": "0.19.0"
  },
  "devDependencies": {
    "html-webpack-plugin": "^5.5.0",
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4",
    "ts-loader": "^9.2.8",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.2"
  }
}
```

* webpack.dev.ts

```typescript
import path from 'path';
import { Configuration } from 'webpack';
import { Configuration as DevServerConfig } from 'webpack-dev-server';
import HtmlWebpackPlugin from "html-webpack-plugin";

declare module 'webpack' {
    interface Configuration {
        devServer?: DevServerConfig | undefined;
    }
}

const config: Configuration = {
    mode: "development",
    entry: path.resolve(__dirname, './src/index.ts'),
    plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, './src/index.html'),
            templateParameters: {},
        }),
    ],
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                exclude: /node_modules/,
            },
        ],
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    devServer: {
        allowedHosts: 'all',
        proxy: {
            '/v1/prom': {
                target: 'https://prometheus.demo.do.prometheus.io',
                pathRewrite: {'^/v1/prom':'/api/v1'},
                changeOrigin: true
            }
        }
    }
}

export default config;
```

And so far I can see the request going to the `series` and `labels` endpoint

![image](https://user-images.githubusercontent.com/4548045/159021303-60f793ce-52a0-4379-89ca-b7c62c185611.png)

To deactivate the query going to the endpoint `/api/v1/metadata`, you can simply set the parameter `maxMetricsMetadata` to 0 :

```typescript
const promQL = new PromQLExtension().setComplete({
    maxMetricsMetadata: 0,
    remote: {
        apiPrefix: '/v1/prom',
        httpMethod: 'GET',
    },
});
```

**Comment by stenwolf** [comment]
Thank you, I see it is calling the `/label` endpoint, I thought it was calling `/labels`. So I was searching for `labels` and didn't see anything popping up. I still don't see the `/series` endpoint being called though. After I set this property from your snippet above `maxMetricsMetadata: 0`, I'm still seeing `/metadata` being called. 

<img width="497" alt="Screen Shot 2022-03-18 at 12 53 42 PM" src="https://user-images.githubusercontent.com/5943678/159075861-d87d3085-08b8-4ca7-915e-0730832c3b1d.png">

Could this be the reason why `/series` endpoint is not being called? Because `/metadata` is returning a 404?

**Comment by Nexucis** [comment]
the autocompletion is calling the different endpoints when it is required and it depends of the context (i.e. of where you are in the PromQL expression). So it can be normal the endpoint `/series` is not called.
To see the endpoint `/series` called, you can try something like that `<insert_a_metric_name>{<start_typing a label>}`, like I  am showing in my example.

**Comment by Nexucis** [comment]
it is also the same notes for the endpoint `/labels` that is indeed called under a certain context. It is basically called with this kind of expression:

`sum by()`.

Other all, to know if your autocompletion is working fine, you should see the list of the metrics proposed, labels or label value depending of the context.

**Comment by stenwolf** [comment]
Ah I see it, thank you very much! It is indeed working as intended. Last thing I wanted to ask is the `/metadata` endpoint, as I'm still seeing it's being called even with `maxMetricsMetadata: 0`, would you mind whenever you have a chance to verify it on your side if it is working correctly please?
This is what I have to setup the promQL extension
```javascript
        const promQL = new PromQLExtension().setComplete({
            maxMetricsMetadata: 0,
            remote: {
                lookbackInterval: 12 * 60 * 60 * 1000 * 1000, // TODO: 12000 hours, change this
                apiPrefix: '/v1/tsdb',
                httpMethod: 'GET',
            },
        });
```

**Comment by stenwolf** [comment]
Ah I see it, thank you very much! It is indeed working as intended.

Last thing I wanted to ask is the `/metadata` endpoint, as I'm still seeing it's being called even with `maxMetricsMetadata: 0`, would you mind whenever you have a chance to verify it on your side if it is working correctly please?
This is what I have to setup the promQL extension
```javascript
        const promQL = new PromQLExtension().setComplete({
            maxMetricsMetadata: 0,
            remote: {
                lookbackInterval: 12 * 60 * 60 * 1000 * 1000, // TODO: 12000 hours, change this
                apiPrefix: '/v1/prom',
                httpMethod: 'GET',
            },
        });
```

**Comment by stenwolf** [comment]
Actually nevermind, I rebuilt my workspace and all is working now, thank you so much for the help!
