### ISSUE TITLE
Update to Codemirror 0.20.X

### ISSUE THREAD

**Issue by 0x0dr1y** [prometheus/codemirror-promql#190]
Codemirror has been updated to v0.20 include some breaking changes which sadly breaks the backward compatibility to this package.

https://discuss.codemirror.net/t/release-0-20-0/4302

**Comment by Nexucis** [comment]
It looks like Codemirror has been released under a stable version (v6). Hopefully that will be the last time we foresee a breaking change.

**Comment by 0x0dr1y** [comment]
> It looks like Codemirror has been released under a stable version (v6). Hopefully that will be the last time we foresee a breaking change.

Nice! 

If you need help upgrading just poke me, i already did it for private use (in a dirty way :joy:). Just a headsup lezer / lezer-promql needs also to be updated.

General question: Where should PRs be created? In the individual repos or in the main prom repo?

**Comment by Nexucis** [comment]
I'm currently working on upgrading codemirror no worries :).
The PR will go to the main prometheus repo.

The main "issue" I would say is more we stopped the sync between the prom main repo and this one. It was needed in order to clean the UI folder in the prom repository.

So another work will be to re enable the publication of this package.

**Comment by Nexucis** [comment]
> If you need help upgrading just poke me, i already did it for private use (in a dirty way 😂)

I guess that's where [lezer-promql20](https://www.npmjs.com/package/lezer-promql20) is coming from :)

**Comment by Nexucis** [comment]
here the PR that is upgrading codemirror and lezer to the latest version: https://github.com/prometheus/prometheus/pull/10841

**Comment by 0x0dr1y** [comment]
Awesome, I'll take a quick look and compare it with my changes later! :) 

I'll also remove my npm packages (which shouldn't be public in the first place) once the updated version is online

**Comment by Nexucis** [comment]
The https://github.com/prometheus/prometheus/pull/10841 has been approved and merged which fixed this issue.
Now we just have to published the new version.

**Comment by 0x0dr1y** [comment]
Awesome, thanks alot! Any idea when this will happen?

**Comment by Nexucis** [comment]
To be able to publish the new version, this PR https://github.com/prometheus/prometheus/pull/10876 needs to be merged
I hope it will be merged before the next Prometheus release that should happen next week.
